# Generated by Django 4.2.2 on 2023-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apPaterno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
            ],
        ),
    ]
