# Generated by Django 4.2.2 on 2023-06-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_keyspc_pedido_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyspc',
            name='rut',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rut',
            field=models.CharField(max_length=11),
        ),
    ]
