# Generated by Django 4.2.2 on 2023-06-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegopc',
            old_name='idpc',
            new_name='idcomputador',
        ),
    ]
