# Generated by Django 4.2.2 on 2023-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('idmanga', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='static/manga')),
                ('precio', models.IntegerField()),
                ('inventario', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
